---
- name: Ensure NTP (for time synchronization) is installed
  apt: pkg=ntp state=installed
  sudo: yes
  tags:
    - ntp

- name: Ensure NTP is running
  service: name=ntp state=started enabled=yes
  sudo: yes
  tags:
    - ntp