---
- name: Ensure Fail2Ban installed
  apt: pkg=fail2ban state=latest
  sudo: yes

- name: Install config
  command: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local creates=/etc/fail2ban/jail.local
  when: 

- name: reload fail2ban
  sudo: yes
  service: name=fail2ban state=reloaded enabled=yes