---
- name: Allow ssh through firewall
  sudo: yes
  ufw: proto=tcp port=22 rule=allow
- name: Allow ssh through firewall (vagrant)
  sudo: yes
  ufw: proto=tcp port=2222 rule=allow
- name: Set ufw policy
  sudo: yes
  ufw: state=enabled direction=incoming policy=deny