- name: install packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - unzip
    - git
    - ack-grep
    - htop
    - vim
    - tree
    - tmux
    - software-properties-common
  tags:
    - utilities